In [6]:
import pandas as pd

In [7]:
dados = pd.read_csv('dados-padaria.csv')

In [8]:
dados.info

<bound method DataFrame.info of        TransactionNo          Items             DateTime    Daypart  DayType
0                  1          Bread  2016-10-30 09:58:11    Morning  Weekend
1                  2   Scandinavian  2016-10-30 10:05:34    Morning  Weekend
2                  2   Scandinavian  2016-10-30 10:05:34    Morning  Weekend
3                  3  Hot chocolate  2016-10-30 10:07:57    Morning  Weekend
4                  3            Jam  2016-10-30 10:07:57    Morning  Weekend
...              ...            ...                  ...        ...      ...
20502           9682         Coffee  2017-09-04 14:32:58  Afternoon  Weekend
20503           9682            Tea  2017-09-04 14:32:58  Afternoon  Weekend
20504           9683         Coffee  2017-09-04 14:57:06  Afternoon  Weekend
20505           9683         Pastry  2017-09-04 14:57:06  Afternoon  Weekend
20506           9684      Smoothies  2017-09-04 15:04:24  Afternoon  Weekend

[20507 rows x 5 columns]>

In [9]:
dados.head()

   TransactionNo          Items             DateTime  Daypart  DayType
0              1          Bread  2016-10-30 09:58:11  Morning  Weekend
1              2   Scandinavian  2016-10-30 10:05:34  Morning  Weekend
2              2   Scandinavian  2016-10-30 10:05:34  Morning  Weekend
3              3  Hot chocolate  2016-10-30 10:07:57  Morning  Weekend
4              3            Jam  2016-10-30 10:07:57  Morning  Weekend

In [10]:
transacao = []
for item in dados ['TransactionNo'].unique():
    lista = list(set(dados[dados['TransactionNo'] == item]['Items']))
    transacao.append(lista)

In [11]:
transacao[0:5]

[['Bread'],
 ['Scandinavian'],
 ['Hot chocolate', 'Cookies', 'Jam'],
 ['Muffin'],
 ['Bread', 'Pastry', 'Coffee']]

In [12]:
from mlxtend.preprocessing import TransactionEncoder

In [13]:
te = TransactionEncoder()

In [14]:
transacao_te = te.fit(transacao).transform(transacao)

In [15]:
transacao_te

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [16]:
transacao_transformado = pd.DataFrame(transacao_te, columns = te.columns_)
transacao_transformado

,Adjustment,Afternoon with the baker,Alfajores,Argentina Night,Art Tray,Bacon,Baguette,Bakewell,Bare Popcorn,Basket,...,The BART,The Nomad,Tiffin,Toast,Truffles,Tshirt,Valentine's card,Vegan Feast,Vegan mincepie,Victorian Sponge
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9460,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9461,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
9462,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9463,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9464,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [17]:
from mlxtend.frequent_patterns import apriori

In [25]:
itens_frequentes_apriori = apriori(transacao_transformado, use_colnames = True, min_support=0.02)
itens_frequentes_apriori.sort_values(['support'], ascending = False)

     support                 itemsets
4   0.478394                 (Coffee)
1   0.327205                  (Bread)
16  0.142631                    (Tea)
3   0.103856                   (Cake)
20  0.090016          (Bread, Coffee)
11  0.086107                 (Pastry)
12  0.071844               (Sandwich)
9   0.061807              (Medialuna)
7   0.058320          (Hot chocolate)
23  0.054728           (Cake, Coffee)
5   0.054411                (Cookies)
31  0.049868            (Tea, Coffee)
29  0.047544         (Pastry, Coffee)
2   0.040042                (Brownie)
6   0.039197             (Farm House)
8   0.038563                  (Juice)
10  0.038457                 (Muffin)
30  0.038246       (Sandwich, Coffee)
0   0.036344              (Alfajores)
28  0.035182      (Medialuna, Coffee)
14  0.034548                  (Scone)
15  0.034443                   (Soup)
17  0.033597                  (Toast)
26  0.029583  (Hot chocolate, Coffee)
21  0.029160          (Bread, Pastry)
13  0.029054           (Scandinavian)
25  0.028209        (Cookies, Coffee)
22  0.028104             (Bread, Tea)
24  0.023772              (Tea, Cake)
32  0.023666          (Toast, Coffee)
19  0.023349            (Bread, Cake)
27  0.020602          (Juice, Coffee)
18  0.020285               (Truffles)

In [26]:
from mlxtend.frequent_patterns import association_rules

In [29]:
regras_apriori = association_rules(itens_frequentes_apriori, metric = 'confidence', min_threshold = 0.5)
regras_apriori

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Cake),(Coffee),0.103856,0.478394,0.054728,0.526958,1.101515,0.005044,1.102664
1,(Cookies),(Coffee),0.054411,0.478394,0.028209,0.518447,1.083723,0.002179,1.083174
2,(Hot chocolate),(Coffee),0.058320,0.478394,0.029583,0.507246,1.060311,0.001683,1.058553
3,(Juice),(Coffee),0.038563,0.478394,0.020602,0.534247,1.116750,0.002154,1.119919
4,(Medialuna),(Coffee),0.061807,0.478394,0.035182,0.569231,1.189878,0.005614,1.210871
5,(Pastry),(Coffee),0.086107,0.478394,0.047544,0.552147,1.154168,0.006351,1.164682
6,(Sandwich),(Coffee),0.071844,0.478394,0.038246,0.532353,1.112792,0.003877,1.115384
7,(Toast),(Coffee),0.033597,0.478394,0.023666,0.704403,1.472431,0.007593,1.764582